export const CREATE_WORKOUT_PLAN_START = 'CREATE_WORKOUT_PLAN_START';
export const CREATE_WORKOUT_PLAN_SUCCESS = 'CREATE_WORKOUT_PLAN_SUCCESS';
export const CREATE_WORKOUT_PLAN_ERROR = 'CREATE_WORKOUT_PLAN_ERROR';