export const CREATE_WORKOUT_PLAN_START = 'CREATE_WORKOUT_PLAN_START';
export const CREATE_WORKOUT_PLAN_SUCCESS = 'CREATE_WORKOUT_PLAN_SUCCESS';
export const CREATE_WORKOUT_PLAN_ERROR = 'CREATE_WORKOUT_PLAN_ERROR';

export const FETCH_WORKOUT_PLAN_START = 'FETCH_WORKOUT_PLAN_START';
export const FETCH_WORKOUT_PLAN_SUCCESS = 'FETCH_WORKOUT_PLAN_SUCCESS';
export const FETCH_WORKOUT_PLAN_ERROR = 'FETCH_WORKOUT_PLAN_ERROR';

export const FETCH_USERS_WORKOUT_PLANS_START = 'FETCH_USERS_WORKOUT_PLANS_START';
export const FETCH_USERS_WORKOUT_PLANS_SUCCESS = 'FETCH_USERS_WORKOUT_PLANS_SUCCESS';
export const FETCH_USERS_WORKOUT_PLANS_ERROR = 'FETCH_USERS_WORKOUT_PLANS_ERROR';